spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        "globally_quoted_identifiers": "true"
  datasource:
    platform: postgres
    url: "jdbc:postgresql://db.tdcsekngtbleusetglnt.supabase.co:5432/postgres?user=postgres&password=wooDe.73/db/"
    username: "postgres"
    password: "wooDe.73/db/"
  database:
    driverClassName: org.Postgresql.Driver
